<Project>
  <PropertyGroup>
    <PulseTradeFSharpCoreVersion>10.1.203</PulseTradeFSharpCoreVersion>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.fsproj'">
    <PackageReference Include="FSharp.Core" Version="$(PulseTradeFSharpCoreVersion)" />
  </ItemGroup>
</Project>
