<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>FSharp.MCP.DevKit.Core</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>0.1.0</Version>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    
    <Compile Include="FileUtils.fs" />
    <Compile Include="FSIService.fs" />
    <Compile Include="FsiActor.fs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FSharp.Compiler.Service">
      <HintPath>C:\Program Files\dotnet\sdk\10.0.200-preview.0.26103.119\FSharp\FSharp.Compiler.Service.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.30" />
    <PackageReference Include="Akka.Remote" Version="1.5.30" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="NuGet.Packaging" Version="6.9.1" />
    <PackageReference Include="FSharp.Core" Version="8.0.400" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSharp.MCP.DevKit.Messages\FSharp.MCP.DevKit.Messages.fsproj" />
  </ItemGroup>

</Project>
